### ISSUE TITLE
python2.7 安装agent出现ImportError: No module named guppy

### ISSUE THREAD

**Issue by gujiwork** [AutohomeRadar/Windows-Agent#7]
C:\Windows-Agent-master>python agent.py install
Traceback (most recent call last):
  File "agent.py", line 14, in <module>
    from utils.threads import (APIThread, BasicCollectThread, IISCollectThread,
  File "C:\Windows-Agent-master\utils\threads.py", line 4, in <module>
    from api.http import app
  File "C:\Windows-Agent-master\api\http.py", line 5, in <module>
    from guppy import hpy
ImportError: No module named guppy

C:\Windows-Agent-master>

**Comment by ninjadq** [comment]
did you installed the requirements before start ? And you can also check the env variable to check if windows-agent proper configured.
